[auth]
site_url = "https://tax-engine-app.netlify.app"
additional_redirect_urls = ["https://tax-engine-app.netlify.app/**", "https://tax-api.catalogshub.com/**", "http://localhost:5173/**", "http://localhost:3737/**"]

[auth.email]
enable_confirmations = false
